0.1.7

diff --git a/local/shopping_cart/.github/workflows/moodle-plugin-ci.yml b/local/shopping_cart/.github/workflows/moodle-plugin-ci.yml
--- a/local/shopping_cart/.github/workflows/moodle-plugin-ci.yml
+++ b/local/shopping_cart/.github/workflows/moodle-plugin-ci.yml
@@ -2,13 +2,13 @@ name: Moodle Plugin CI
 
 on: [push, pull_request]
 
-concurrency: 
+concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 
 jobs:
   test:
-    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/USI' || github.ref == 'refs/heads/dev_testing' || startsWith(github.ref, 'refs/heads/MOODLE')
+    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/USI' || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/MOODLE')
 
     runs-on: ubuntu-22.04
 
@@ -199,5 +199,25 @@ jobs:
         run: moodle-plugin-ci phpunit
 
       - name: Behat features
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci behat --profile chrome
+        ## Run --dump to get faild page HTML in the output stream
+        ## run: moodle-plugin-ci behat --profile chrome --dump
+
+      - name: Upload Behat Faildump
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: Behat Faildump (${{ join(matrix.*, ', ') }})
+          path: ${{ github.workspace }}/moodledata/behat_dump
+          retention-days: 2
+          if-no-files-found: ignore
+
+      # Inwoke remote SSH connection if necessary
+      #- name: Setup tmate session
+      #  if: ${{ failure() }}
+      #  uses: mxschmitt/action-tmate@v3
+
+      - name: Mark cancelled jobs as failed.
+        if: ${{ cancelled() }}
+        run: exit 1
